version: "3.8"
services:
    database:
      image: postgres:16.0
      container_name: database-psql
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 10s
      env_file:
        - .env.example
      volumes:
          - ./postgres-data:/var/lib/postgresql/data
    application:
        container_name: server-fastapi
        restart: always
        env_file:
          - .env.example
        build:
          context: ./
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
          interval: 10s
          timeout: 5s
          retries: 5
        ports:
            - 8000:8000
        depends_on:
          database:
            condition: service_healthy
volumes:
  postgres-data:
    external: true
